export const dark = {
    colors:{
        titleColor : '#FFFFFF',
        bgColor: '#110820',
        altbgColor: '#1a0f2d',
        subColor: '#9BA2AD',
        blogColor: '#110820',
        blogBorder: '#110820',
        itemBg: '#19102D',
        itemBrdr: '#1a102d',
        volBg: '#080213',
        volSub: '#9BA2AD',
        volMain: '#FFFFFF',
        wallColr: '#7B0A75',
        wallBtn: '#7B0A75',
        wallText: '#FFFFFF',
        wallBorder: '#19102D',
        searchColr: '#19102D',
        sideBg: '#080213',
        sideActive: '#ffffff',
        sideBorder: '#080213',
        footerBorder: '#080213',
        colText: '#FFFFFF',
        colBorder: '#080213',
        topAuthor: '#7B0A75',
        backSubBtn: '#7B0A75',
        backSubColor: '#FFFFFF',
        backSubBorder: '#7B0A75',
        btnBorder: '#7B0A75',
        btnTitle: '#7B0A75',
        btnBg: '#7B0A75',
        btnbgTitle: '#FFFFFF',
        brdGeneral: '#1a0f2d',
        genColor: '#9BA2AD',
        priceColor: '#FFFFFF',
        altpriceColor: '#9BA2AD',
        activeTab: '#FFFFFF',
        inActiveTab: '#9BA2AD',
        profileBack: '#1a102d',
        profileBrd: '#2d1d4c',
        linkClr: '#FFFFFF',
        linkhvrClr: '#FFFFFF',
        muiSvgColor: '#9BA2AD',
    },
    images:{
        logoImg: 'url("/beta-logo-white.svg")',
        wallImg: 'url("/new/empty-wallet-white.svg")',
        wallArrowDown: 'url("/new/pf-arrow-down-white.svg")',
        sideActColImg: 'url("/new/sidebar/collections-white.svg")',
        sideActAucImg: 'url("/new/sidebar/auctions-white.svg")',
        sideActCreImg: 'url("/new/sidebar/creators-white.svg")',
        sideActAppImg: 'url("/new/sidebar/apply-listing-white.svg")',
        sideActApAuImg: 'url("/new/sidebar/apply-auction-white.svg")',
        sideActIntImg: 'url("/new/sidebar/introduction-white.svg")',
        sideActWallImg: 'url("/new/sidebar/wallet-white.svg")',
        sideActClockImg: 'url("/new/sidebar/clock-white.svg")',
        sideColImg: 'url("/new/sidebar/collections-white.svg")',
        sideAucImg: 'url("/new/sidebar/auctions-white.svg")',
        sideCreImg: 'url("/new/sidebar/creators-white.svg")',
        sideAppImg: 'url("/new/sidebar/apply-listing-white.svg")',
        sideApAuImg: 'url("/new/sidebar/apply-auction-white.svg")',
        sideIntImg: 'url("/new/sidebar/introduction-white.svg")',
        sideWallImg: 'url("/new/sidebar/wallet-white.svg")',
        sideClockImg: 'url("/new/sidebar/clock-white.svg")',
        closeImg: 'url("/new/close-icon-white.svg")',
    }
}

export const light = {
    colors:{
        titleColor : '#052251',
        bgColor: '#FFFFFF',
        altbgColor: '#f3f6f7',
        subColor: '#052251',
        blogColor: 'rgba(247,249,250,0.7)',
        blogBorder: '#ecf0f1',
        itemBg: '#FFFFFF',
        itemBrdr: '#e4e4e4',
        volBg: '#F7F9FA',
        volSub: '#7B0A75',
        volMain: '#9BA2AD',
        wallBtn: '#7B0A75',
        wallColr: '#FFFFFF',
        wallText: '#FFFFFF',
        wallBorder: '#F3F3F3',
        searchColr: '#F7F9FA',
        sideBg: '#F7F9FA',
        sideActive: '#7B0A75',
        sideBorder: '#F3F3F3',
        footerBorder: '#F3F3F3',
        colText: '#052251',
        colBorder: '#ECF0F1',
        topAuthor: '#052251',
        backSubBtn: '#FFFFFF',
        backSubColor: '#7B0A75',
        backSubBorder: '#7B0A75',
        btnBorder: '#7B0A75',
        btnTitle: '#7B0A75',
        btnBg: '#7B0A75',
        btnbgTitle: '#FFFFFF',
        brdGeneral: '#f3f6f7',
        genColor: '#9BA2AD',
        priceColor: '#7B0A75',
        altpriceColor: '#7B0A75',
        activeTab: '#7B0A75',
        inActiveTab: '#9BA2AD',        
        profileBack: '#FFFFFF',
        profileBrd: '#F3F3F3',
        linkClr: '#052251',
        linkhvrClr: '#7B0A75',
        muiSvgColor: '#9BA2AD',
    },
    images:{
        logoImg: 'url("/beta-logo.svg")',
        wallImg: 'url("/new/empty-wallet-white.svg")',
        wallArrowDown: 'url("/new/pf-arrow-down.svg")',
        sideActColImg: 'url("/new/sidebar/collections.svg")',
        sideActAucImg: 'url("/new/sidebar/auctions.svg")',
        sideActCreImg: 'url("/new/sidebar/creators.svg")',
        sideActAppImg: 'url("/new/sidebar/apply-listing.svg")',
        sideActApAuImg: 'url("/new/sidebar/apply-auction.svg")',
        sideActIntImg: 'url("/new/sidebar/introduction.svg")',
        sideActWallImg: 'url("/new/sidebar/wallet.svg")',
        sideActClockImg: 'url("/new/sidebar/clock.svg")',
        sideColImg: 'url("/new/sidebar/collections-normal.svg")',
        sideAucImg: 'url("/new/sidebar/auctions-normal.svg")',
        sideCreImg: 'url("/new/sidebar/creators-normal.svg")',
        sideAppImg: 'url("/new/sidebar/apply-listing-normal.svg")',
        sideApAuImg: 'url("/new/sidebar/apply-auction-normal.svg")',
        sideIntImg: 'url("/new/sidebar/introduction-normal.svg")',
        sideWallImg: 'url("/new/sidebar/wallet-normal.svg")',
        sideClockImg: 'url("/new/sidebar/clock-normal.svg")',
        closeImg: 'url("/new/close-icon-black.svg")',
    }
}